version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: test
    networks:
    - backend
    
  app:
    image: praqma/network-multitool
    container_name: network-multitool
    restart: always
    links:
    - db
    networks:
    - backend
    - frontend
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
    - frontend

networks:
  frontend: 
    driver: bridge
  backend:
    driver: bridge